### ISSUE TITLE
Where to put docs that are not FHIR release / EHR platform dependent?

### ISSUE THREAD

**Issue by whitehatguy** [cerner/fhir.cerner.com#103]
I've been having to do dual-maintenance of the authorization doc in the two release folders - is there a way that we can link to the authorization guides and put in somewhere else in the site hierarchy?  I'm not familiar enough with nanoc - when I try and move one of the documents up a level, it gives unknownlayout errors.  Additionally, is there a location I should choose such that the documentation is shared between both Millennium and Soarian?

**Comment by daliboz** [comment]
We already copy some documentation around when the site is building - so we can do this for common documentation. However, we don't need this quite yet (there are some differences between authorization capabilities in May and DSTU 2 final). Agree we need to consider this for the future and have moved the tracker internally.
