### ISSUE TITLE
Get Slot Information & Scheudle

### ISSUE THREAD

**Issue by ericmontepanda** [cerner/fhir.cerner.com#377]
Are there examples in the existing FHIR environment to be able to search for appointments by practitioner (Schedule.actor) and specific slot-type?

I tried looking for slots with this example:
Slot?start=2020&slot-type=http://snomed.info/sct|394602003&_count=5

And after finding the slot Id and receiving the schedule information, I want to know the schedule.actor but it doesn't show any, except for a name.

Can we get better examples on leveraging: Schedule.actor, slot-type, and locations? Previously there were sample data and now it no longer exists. For example this slot-type:
https://fhir.cerner.com/{{tenant}}/codeSet/14249|4062744 

used to work.

**Comment by FFSol** [comment]
Per [DSTU2 Slot documentation](https://fhir.cerner.com/millennium/dstu2/scheduling/slot/#example):

```Slot?schedule.actor=Practitioner/2578010&start=2019&slot-type=http://snomed.info/sct|408443003&_count=5```

Here is an example with location parameter:

```Slot?schedule.actor=Practitioner/4980007&start=2019&slot-type=http://snomed.info/sct|408443003&-location=4048128&_count=5```

**Comment by ericmontepanda** [comment]
`Slot?schedule.actor=Practitioner/2578010&start=2019&slot-type=http://snomed.info/sct|408443003&_count=5`

Does not result in any slots for start dates in 2019 or 2020.
