### ISSUE TITLE
404 on the link to Java FHIR Client

### ISSUE THREAD

**Issue by LaurenceL** [cerner/fhir.cerner.com#545]
On the page SMART (https://fhir.cerner.com/smart/), in the section "Open Source FHIR Client Libraries", the link for Java: http://hapifhir.io/doc_rest_client.html produce a 404.

The documentation seems to have change format. Maybe something like this would be a better new url:
https://hapifhir.io/hapi-fhir/docs/server_plain/rest_operations.html

**Comment by MaxPhilips** [comment]
thanks for reporting @LaurenceL - i've updated the link for HAPI to take browsers to HAPI's GitHub repo. i will deploy this change to the live site yet today
