### ISSUE TITLE
Document browser recommendations

### ISSUE THREAD

**Issue by mbeerman** [cerner/fhir.cerner.com#58]
We should consider documenting the browsers (w/ versions) that Cerner supports/certifies/recommends for FHIR application developers (and users).

Of particular note: Launching into a native application from a web browser is _not_ fully supported on Internet Explorer 10 and earlier, and we're already aware of FHIR applications that rely on that capability. If that weren't reason enough, Microsoft has announced the end of support for Internet Explorer 10 and earlier, and those browsers will become ever more insecure over time. Everyone in the FHIR ecosystem bears a responsibility to lead users to the most safe, secure, reliable computing environments possible.

[1] https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by daliboz** [comment]
Note: this has been moved internally for a general SMART FAQ that would describe this. Agree it's needed
