### ISSUE TITLE
3rd, 4th, 5th, 6th level headers?

### ISSUE THREAD

**Issue by whitehatguy** [cerner/fhir.cerner.com#98]
Current examples of markdown pages generally start with the third header (``###``).  Once the markdown is generated into HTML via nanoc, there's no discernible difference between h3 and h4, and h5 and h6, respectively.  This makes the nesting of documentation difficult to read.  It could be possible to reduce this confusion through the additional of numbers in the headers, but that interferes with the table of contents.

Any recommendations on how to make this more clear?

**Comment by MaxPhilips** [comment]
I think only the authorization page jumps from h1 to h3 like that.  I would say feel free to update the heading levels to whatever's readable as part of any changes you make to pages.

If there's still a conflict between header levels, we can update the [CSS](https://github.com/cerner/fhir.cerner.com/blob/master/static/css/documentation.css) to differentiate them.

**Comment by whitehatguy** [comment]
Moving things to start at the 2nd header level works much better, including the generation of table of contents.  This seems sufficient.
